/*
 * jquery.tween.js v0.1.1
 * 
 * A jQuery plugin provides a stylish and unified animation for your browser based app.
 *
 * https://github.com/after12am/jquery.tween.js
 *
 * Copyright 2012-2015 Satoshi Okami
 * Released under the MIT license
 */
(function(c){function y(){this.y=this.x=0;this.rotatey=this.rotatex=null;this.skewy=this.skewx=this.scaley=this.scalex=this.rotatez=0}function z(a){this.elem=a;this.src=c(a).data("tween:transform")||d.factory();this.dest=d.factory();this.matrix=new p;this.def={x:c(a).data("tween:def.x")||c(a).data("tween:def.x",parseInt(c(a).css("left"),10)||0).data("tween:def.x"),y:c(a).data("tween:def.y")||c(a).data("tween:def.y",parseInt(c(a).css("top"),10)||0).data("tween:def.y")}}function A(a,b){(new z(a)).animate(b.props,
b.duration,b.delay,b.easing,b.complete)}function C(a){return function(){var b=n(this.style,"transition")in this.style,b=c.fn.tween.debug.animateType||(b?"transition":"animation");switch(t){case "o":return A(this,a)}switch(b){case "transition":var b=c(this).data("tween:transform")||d.factory(),f=new u(this);f.style(a.style);f.transform(b.update(a.props).toString());for(var v in a.props)b[v]||"perspective"===v||f.set(v,a.props[v]);void 0!=a.props.origin&&c(this).css(n(this.style,"transform-origin"),
a.props.origin);void 0!=a.props.perspective&&c(this).parent().css(n(this.style,"perspective"),a.props.perspective);f.transit(a.duration,a.delay,a.easing,a.complete);c(this).data("tween:transform",b);break;case "animation":return A(this,a)}}}function u(a){this.elem=a;this.styles={}}var n=function(a,b){var f=["Webkit","O","Moz","ms"];if(b in a)return b;for(var c=b.charAt(0).toUpperCase()+b.slice(1),d=b,h=f.length;h--;)if(b=f[h]+c,b in a)return b;return d},t=function(){if(window.getComputedStyle){var a=
window.getComputedStyle(document.documentElement,"");return(Array.prototype.slice.call(a).join("").match(/-(moz|webkit|ms)-/)||""===a.OLink&&["","o"])[1]}}();(function(){var a=c("<div>")[0],b={webkit:"webkitTransitionEnd",moz:"transitionend",ms:"msTransitionEnd",o:"webkitTransitionEnd"},f;for(f in b)if(t===f)return b[f];if("transitionend"in a.style)return"transitionend"})();var B=!!window.navigator.userAgent.toLowerCase().match(/msie/),q=function(){var a=Math.PI/180;return function(b){return b*a}}();
(function(){var a=180/Math.PI;return function(b){return b*a}})();var w=function(){var a=Math.pow(10,3);return function(b){return Math.round(b*a)/a}}();y.prototype={center:function(a){var b=0,f=0,d=0,r=0,h=a.matrix.toArray(),d=d+(h[4]+a.def.x),r=r+(h[5]+a.def.y);if(this.scalex||this.rotatey||this.skewx)b=-(parseInt(c(a.elem).width(),10)-a.src.width)/2;if(this.scaley||this.rotatex||this.skewy)f=-(parseInt(c(a.elem).height(),10)-a.src.height)/2;this.rotatez&&(b=-(a.elem.offsetWidth/2)+a.elem.clientWidth/
2,f=-(a.elem.offsetHeight/2)+a.elem.clientHeight/2);c(a.elem).css({left:g("%spx",d),top:g("%spx",r),marginLeft:g("%spx",b),marginTop:g("%spx",f)})}};z.prototype={set:function(a,b){var f=n(this.elem.style,a);c(this.elem).css(f,b);return this},get:function(a){a=n(this.elem.style,a);return c(this.elem).css(a)},transform:function(a){a=a.toArray();for(var b=0;b<a.length;b++)a[b]=w(a[b]);this.set("transform",g("matrix(%s,%s,%s,%s,%s,%s)",a[0],a[1],a[2],a[3],a[4],a[5]))},dxImageTransform:function(a){a=a.toArray();
for(var b=0;b<a.length;b++)a[b]=w(a[b]);this.set("filter",g("progid:DXImageTransform.Microsoft.Matrix(M11=%s, M12=%s, M21=%s, M22=%s,sizingMethod='auto expand');",a[0],a[2],a[1],a[3]))},animate:function(a,b,f,d,r){this.dest.update(a);this.src.width=parseInt(c(this.elem).width(),10);this.src.height=parseInt(c(this.elem).height(),10);var h={},e;for(e in a)e in this.dest&&(h["__"+e]=this.dest[e]-this.src[e]);for(e in a)this.dest[e]||(h[e]=a[e]);parseInt(c(this.elem).css("margin"))&&c(this.elem).css("margin",
"0");c(this.elem).delay(f).animate(c.extend(h,{___update:!0}),{duration:b,easing:d,complete:this.complete(this,r),step:this.update(this,new y)});c(this.elem).dequeue()},update:function(a,b){return function(f,c){var d=c.prop.replace(/__/,"");d in a.src&&(b[d]=f);"_update"!==d&&(a.matrix=new p,a.matrix=a.matrix.translate({x:b.x+a.src.x,y:b.y+a.src.y}),a.matrix=a.matrix.rotate(q(b.rotatez+a.src.rotatez)),a.matrix=null!==b.rotatex||null!==b.rotatey?a.matrix.scale({x:Math.cos(q((b.rotatey||0)+a.src.rotatey)),
y:Math.cos(q((b.rotatex||0)+a.src.rotatex))}):a.matrix.scale({x:b.scalex+a.src.scalex,y:b.scaley+a.src.scaley}),a.matrix=a.matrix.skew({x:q(b.skewx+a.src.skewx),y:q(b.skewy+a.src.skewy)}),B?(a.dxImageTransform(a.matrix),b.center(a)):a.transform(a.matrix))}},complete:function(a,b){return function(){c(a.elem).data("tween:transform",a.dest);c.proxy(b,a.elem)()}}};if(!c.cssHooks)throw"jQuery 1.4.3 or above is required for this plugin to work";c.cssHooks.x={get:function(a,b,f){return(c(a).data("tween:transform")||
d.factory()).x},set:function(a,b){c(a).tween({x:parseInt(b,10)},0)}};c.cssHooks.y={get:function(a,b,f){return(c(a).data("tween:transform")||d.factory()).y},set:function(a,b){c(a).tween({y:parseInt(b,10)},0)}};c.cssHooks.z={get:function(a,b,f){return(c(a).data("tween:transform")||d.factory()).z},set:function(a,b){c(a).tween({z:parseInt(b,10)},0)}};c.cssHooks.rotate={get:function(a,b,f){return(c(a).data("tween:transform")||d.factory()).rotatez},set:function(a,b){c(a).tween({rotatez:parseInt(b,10)},
0)}};c.cssHooks.rotatex={get:function(a,b,f){return(c(a).data("tween:transform")||d.factory()).rotatex},set:function(a,b){c(a).tween({rotatex:parseInt(b,10)},0)}};c.cssHooks.rotatey={get:function(a,b,f){return(c(a).data("tween:transform")||d.factory()).rotatey},set:function(a,b){c(a).tween({rotatey:parseInt(b,10)},0)}};c.cssHooks.rotatez={get:function(a,b,f){return(c(a).data("tween:transform")||d.factory()).rotatez},set:function(a,b){c(a).tween({rotatez:parseInt(b,10)},0)}};c.cssHooks.scale={get:function(a,
b,f){a=c(a).data("tween:transform")||d.factory();return{x:a.scalex,y:a.scaley}},set:function(a,b){c(a).tween({scalex:parseInt(b,10),scaley:parseInt(b,10)},0)}};c.cssHooks.scalex={get:function(a,b,f){return(c(a).data("tween:transform")||d.factory()).scalex},set:function(a,b){c(a).tween({scalex:parseInt(b,10)},0)}};c.cssHooks.scaley={get:function(a,b,f){return(c(a).data("tween:transform")||d.factory()).scaley},set:function(a,b){c(a).tween({scaley:parseInt(b,10)},0)}};c.cssHooks.skew={get:function(a,
b,f){a=c(a).data("tween:transform")||d.factory();return{x:a.skewx,y:a.skewy}},set:function(a,b){c(a).tween({skewx:parseInt(b,10),skewy:parseInt(b,10)},0)}};c.cssHooks.skewx={get:function(a,b,f){return(c(a).data("tween:transform")||d.factory()).skewx},set:function(a,b){c(a).tween({skewx:parseInt(b,10)},0)}};c.cssHooks.skewy={get:function(a,b,f){return(c(a).data("tween:transform")||d.factory()).skewy},set:function(a,b){c(a).tween({skewy:parseInt(b,10)},0)}};q=function(){var a=Math.PI/180;return function(b){return b*
a}}();(function(){var a=180/Math.PI;return function(b){return b*a}})();var w=function(){var a=Math.pow(10,3);return function(b){return Math.round(b*a)/a}}(),p=function(a){this.base=a||[1,0,0,0,1,0]};p.prototype={_multiply:function(a,b,f,c,d,h,e,g,m,l,k,n){return new p([a*e+b*l,a*g+b*k,a*m+b*n+f,c*e+d*l,c*g+d*k,c*m+d*n+h])},multiply:function(a){return this._multiply.apply(this,this.base.concat(a))},translate:function(a){return this.multiply([1,0,a.x,0,1,a.y])},rotate:function(a){var b=Math.sin(a);
a=Math.cos(a);return this.multiply([a,b,0,-b,a,0])},scale:function(a){return this.multiply([a.x,0,0,0,a.y,0])},skew:function(a){return this.multiply([1,a.y||0,0,a.x||0,1,0])},toArray:function(){var a=this.base;return[a[0],a[1],a[3],a[4],a[2],a[5]]}};p.parseArray=function(a){return new p([a[0],a[1],a[4],a[2],a[3],a[5]])};Object.create||(Object.create=function(a){function b(){}if(1<arguments.length)throw Error("Object.create implementation only accepts the first parameter.");b.prototype=a;return new b});
var d=function(){this.rotatez=this.rotatey=this.rotatex=this.z=this.y=this.x=0;this.scalez=this.scaley=this.scalex=1;this.skewy=this.skewx=0;this.origin="50% 50%";this.perspective="none"};d.factory=function(){switch(t){case "o":return new x;default:return new d}};d.prototype.toAbs=function(a,b){var f;if("string"===typeof b&&(f=b.match(/^\s*(\+|-)=\s*([0-9]+)\s*$/)))switch(f[1]){case "+":b=this[a]+ +f[2];break;case "-":b=this[a]-+f[2]}return+b};d.prototype.set=function(a,b){this[a]=b;return this};
d.prototype.update=function(a){for(var b in a)void 0!==this[b]&&"function"!==typeof this[b]&&this.set(b,this.toAbs(b,a[b]));return this};d.prototype.translate=function(){return g("translate(%spx,%spx)",this.x,this.y)};d.prototype.translateX=function(){return g("translateX(%spx)",this.x)};d.prototype.translateY=function(){return g("translateY(%spx)",this.y)};d.prototype.translateZ=function(){return g("translateZ(%spx)",this.z)};d.prototype.translate3d=function(){return g("translate3d(%spx,%spx,%spx)",
this.x,this.y,this.z)};d.prototype.rotateX=function(){return g("rotateX(%sdeg)",this.rotatex)};d.prototype.rotateY=function(){return g("rotateY(%sdeg)",this.rotatey)};d.prototype.rotateZ=function(){return g("rotateZ(%sdeg)",this.rotatez)};d.prototype.scale=function(){return g("scale(%s,%s)",this.scalex,this.scaley)};d.prototype.scaleX=function(){return g("scaleX(%s)",this.scalex)};d.prototype.scaleY=function(){return g("scaleY(%s)",this.scaley)};d.prototype.scaleZ=function(){return g("scaleZ(%s)",
this.scalez)};d.prototype.scale3d=function(){return g("scale3d(%s,%s,%s)",this.scalex,this.scaley,this.scalez)};d.prototype.skew=function(){return g("skew({x}deg,{y}deg)",this.skewx,this.skewy)};d.prototype.skewX=function(){return g("skewX(%sdeg)",this.skewx)};d.prototype.skewY=function(){return g("skewY(%sdeg)",this.skewy)};d.prototype.toString=function(){return[this.translate3d(),this.rotateX(),this.rotateY(),this.rotateZ(),this.scale(),this.skewX(),this.skewY()].join(" ")};var x=function(){d.call(this)};
x.prototype=Object.create(d.prototype);x.prototype.toString=function(){return[this.translate(),this.rotateZ(),this.scale(),this.skewX(),this.skewY()].join(" ")};u.cubicBezier={def:this["ease-out-quad"],"in":"ease-in",out:"ease-out","in-out":"ease-in-out",linear:"cubic-bezier(0.250, 0.250, 0.750, 0.750)","ease-in-quad":"cubic-bezier(0.550, 0.085, 0.680, 0.530)","ease-in-cubic":"cubic-bezier(0.550, 0.055, 0.675, 0.190)","ease-in-quart":"cubic-bezier(0.895, 0.030, 0.685, 0.220)","ease-in-quint":"cubic-bezier(0.755, 0.050, 0.855, 0.060)",
"ease-in-sine":"cubic-bezier(0.470, 0.000, 0.745, 0.715)","ease-in-expo":"cubic-bezier(0.950, 0.050, 0.795, 0.035)","ease-in-circ":"cubic-bezier(0.600, 0.040, 0.980, 0.335)","ease-in-back":"cubic-bezier(0.600, -0.280, 0.735, 0.045)","ease-out-quad":"cubic-bezier(0.250, 0.460, 0.450, 0.940)","ease-out-cubic":"cubic-bezier(0.215, 0.610, 0.355, 1.000)","ease-out-quart":"cubic-bezier(0.165, 0.840, 0.440, 1.000)","ease-out-quint":"cubic-bezier(0.230, 1.000, 0.320, 1.000)","ease-out-sine":"cubic-bezier(0.390, 0.575, 0.565, 1.000)",
"ease-out-expo":"cubic-bezier(0.190, 1.000, 0.220, 1.000)","ease-out-circ":"cubic-bezier(0.075, 0.820, 0.165, 1.000)","ease-out-back":"cubic-bezier(0.175, 0.885, 0.320, 1.275)","ease-in-out-quad":"cubic-bezier(0.455, 0.030, 0.515, 0.955)","ease-in-out-cubic":"cubic-bezier(0.645, 0.045, 0.355, 1.000)","ease-in-out-quart":"cubic-bezier(0.770, 0.000, 0.175, 1.000)","ease-in-out-quint":"cubic-bezier(0.860, 0.000, 0.070, 1.000)","ease-in-out-sine":"cubic-bezier(0.445, 0.050, 0.550, 0.950)","ease-in-out-expo":"cubic-bezier(1.000, 0.000, 0.000, 1.000)",
"ease-in-out-circ":"cubic-bezier(0.785, 0.135, 0.150, 0.860)","ease-in-out-back":"cubic-bezier(0.680, -0.550, 0.265, 1.550)"};u.prototype={set:function(a,b){var f=n(this.elem.style,a);this.styles[f]=b;return this},get:function(a){a=n(this.elem.style,a);return this.styles[a]},duration:function(a,b){if(void 0===a)return parseInt(this.get("transition-duration"),10);this.set("transition-duration",g("%s%s",a,void 0===b?"ms":""));return this},delay:function(a,b){if(void 0===a)return parseInt(this.get("transition-delay"),
10);this.set("transition-delay",g("%s%s",a,void 0===b?"ms":""));return this},easing:function(a){if(void 0===a)return this.get("transition-timing-function");this.set("transition-timing-function",u.cubicBezier[a]);return this},property:function(a){if(void 0===a)return this.get("transition-property");this.set("transition-property",a);return this},style:function(a){if(void 0===a)return this.get("transform-style");this.set("transform-style",a);return this},transform:function(a){if(void 0===a)return this.get("transform");
this.set("transform",a);return this},transit:function(a,b,f,d){this.duration(a);this.delay(b);this.easing(f);c(this.elem).css(this.styles);if(0===this.duration())for(b=0,a=n(this.elem.style,"transition-duration");50<++b&&0!==parseInt(c(this.elem).css(a),10););setTimeout(c.proxy(this.complete(this,d),this.elem),this.duration());return this},complete:function(a,b){return function(){c.proxy(b,this)();c(this).dequeue();0===c(this).queue().length&&a.clear()}},clear:function(){this.duration("","").delay("",
"").easing("").property("");c(this.elem).css(this.styles)}};c.fn.tween=function(a,b,f,d){"function"===typeof b&&(d=b,b=void 0);"function"===typeof f&&(d=f,f=void 0);switch(typeof b){case "number":break;case "string":b=c.fx.speeds[b]||c.fx.speeds._default;break;default:b=c.fx.speeds._default}var g=c.extend(!0,{},a),h;for(h in a){switch(h){case "rotate":g.rotatez=a[h];break;case "scale":g.scalex=g.scaley=a[h];break;case "skew":g.skewx=g.skewy=a[h];break;default:continue}delete g[h]}return this.queue(C({props:g||
{},duration:b,delay:0,easing:f||"def",style:"flat",property:"all",complete:d||function(){}}))};c.fn.tween.debug={animateType:""};n=function(a,b){var f=["Webkit","O","Moz","ms"];if(b in a)return b;for(var c=b.charAt(0).toUpperCase()+b.slice(1),d=b,h=f.length;h--;)if(b=f[h]+c,b in a)return b;return d};t=function(){if(window.getComputedStyle){var a=window.getComputedStyle(document.documentElement,"");return(Array.prototype.slice.call(a).join("").match(/-(moz|webkit|ms)-/)||""===a.OLink&&["","o"])[1]}}();
(function(){var a=c("<div>")[0],b={webkit:"webkitTransitionEnd",moz:"transitionend",ms:"msTransitionEnd",o:"webkitTransitionEnd"},f;for(f in b)if(t===f)return b[f];if("transitionend"in a.style)return"transitionend"})();var B=!!window.navigator.userAgent.toLowerCase().match(/msie/),g=function(){function a(a){return Object.prototype.toString.call(a).slice(8,-1).toLowerCase()}var b=function(){b.cache.hasOwnProperty(arguments[0])||(b.cache[arguments[0]]=b.parse(arguments[0]));return b.format.call(null,
b.cache[arguments[0]],arguments)};b.object_stringify=function(a,c,d,h){var e="";if(null!=a)switch(typeof a){case "function":return"[Function"+(a.name?": "+a.name:"")+"]";case "object":if(a instanceof Error)return"["+a.toString()+"]";if(c>=d)return"[Object]";h&&(h=h.slice(0),h.push(a));if(null!=a.length){var e=e+"[",g=[],m;for(m in a)h&&0<=h.indexOf(a[m])?g.push("[Circular]"):g.push(b.object_stringify(a[m],c+1,d,h));e+=g.join(", ")+"]"}else{if("getMonth"in a)return"Date("+a+")";var e=e+"{",g=[],l;
for(l in a)a.hasOwnProperty(l)&&(h&&0<=h.indexOf(a[l])?g.push(l+": [Circular]"):g.push(l+": "+b.object_stringify(a[l],c+1,d,h)));e+=g.join(", ")+"}"}return e;case "string":return'"'+a+'"'}return""+a};b.format=function(c,d){var r=1,h=c.length,e="",n=[],m,l,k,p;for(m=0;m<h;m++)if(e=a(c[m]),"string"===e)n.push(c[m]);else if("array"===e){k=c[m];if(k[2])for(e=d[r],l=0;l<k[2].length;l++){if(!e.hasOwnProperty(k[2][l]))throw Error(g('[sprintf] property "%s" does not exist',k[2][l]));e=e[k[2][l]]}else e=k[1]?
d[k[1]]:d[r++];if(/[^sO]/.test(k[8])&&"number"!=a(e))throw Error(g('[sprintf] expecting number but found %s "'+e+'"',a(e)));switch(k[8]){case "b":e=e.toString(2);break;case "c":e=String.fromCharCode(e);break;case "d":e=parseInt(e,10);break;case "e":e=k[7]?e.toExponential(k[7]):e.toExponential();break;case "f":e=k[7]?parseFloat(e).toFixed(k[7]):parseFloat(e);break;case "O":e=b.object_stringify(e,0,parseInt(k[7])||5);break;case "o":e=e.toString(8);break;case "s":e=(e=String(e))&&k[7]?e.substring(0,
k[7]):e;break;case "u":e=Math.abs(e);break;case "x":e=e.toString(16);break;case "X":e=e.toString(16).toUpperCase()}e=/[def]/.test(k[8])&&k[3]&&0<=e?"+"+e:e;l=k[4]?"0"==k[4]?"0":k[4].charAt(1):" ";p=k[6]-String(e).length;if(k[6]){for(var q=[];0<p;q[--p]=l);l=q.join("")}else l="";n.push(k[5]?e+l:l+e)}return n.join("")};b.cache={};b.parse=function(a){for(var b=[],c=[],d=0;a;){if(null!==(b=/^[^\x25]+/.exec(a)))c.push(b[0]);else if(null!==(b=/^\x25{2}/.exec(a)))c.push("%");else if(null!==(b=/^\x25(?:([1-9]\d*)\$|\(([^\)]+)\))?(\+)?(0|'[^$])?(-)?(\d+)?(?:\.(\d+))?([b-fosOuxX])/.exec(a))){if(b[2]){var d=
d|1,e=[],g=b[2],m=[];if(null!==(m=/^([a-z_][a-z_\d]*)/i.exec(g)))for(e.push(m[1]);""!==(g=g.substring(m[0].length));)if(null!==(m=/^\.([a-z_][a-z_\d]*)/i.exec(g)))e.push(m[1]);else if(null!==(m=/^\[(\d+)\]/.exec(g)))e.push(m[1]);else throw Error("[sprintf] "+g);else throw Error("[sprintf] "+g);b[2]=e}else d|=2;if(3===d)throw Error("[sprintf] mixing positional and named placeholders is not (yet) supported");c.push(b)}else throw Error("[sprintf] "+a);a=a.substring(b[0].length)}return c};return b}()})(jQuery);
