/*
 * jquery.tween.js v0.1.3
 * 
 * A jQuery plugin provides a stylish and unified animation for your browser based app.
 *
 * https://github.com/after12am/jquery.tween.js
 *
 * Copyright 2012-2015 Satoshi Okami
 * Released under the MIT license
 */
(function(c){function v(){this.y=this.x=0;this.rotatey=this.rotatex=null;this.skewy=this.skewx=this.scaley=this.scalex=this.rotatez=0}function w(a){this.elem=a;this.src=c(a).data("tween:transform")||d.factory();this.dest=d.factory();this.matrix=new q;this.def={x:c(a).data("tween:def.x")||c(a).data("tween:def.x",parseInt(c(a).css("left"),10)||0).data("tween:def.x"),y:c(a).data("tween:def.y")||c(a).data("tween:def.y",parseInt(c(a).css("top"),10)||0).data("tween:def.y")}}function x(a,b){(new w(a)).animate(b.props,
b.duration,b.delay,b.easing,b.complete)}function e(){var a=c.makeArray(arguments),b=a.shift(),f;for(f in a)b=b.replace("%s",a[f]);return b}function z(a){return function(){var b=k(this.style,"transition")in this.style,b=c.fn.tween.debug.animateType||(b?"transition":"animation");switch(n){case "o":return x(this,a)}switch(b){case "transition":var b=c(this).data("tween:transform")||d.factory(),f=new p(this);f.style(a.style);f.transform(b.update(a.props).toString());for(var t in a.props)void 0===b[t]&&
"perspective"!==t&&f.set(t,a.props[t]);void 0!=a.props.origin&&c(this).css(k(this.style,"transform-origin"),a.props.origin);void 0!=a.props.perspective&&c(this).parent().css(k(this.style,"perspective"),a.props.perspective);f.transit(a.duration,a.delay,a.easing,a.complete);c(this).data("tween:transform",b);break;case "animation":return x(this,a)}}}function p(a){this.elem=a;this.styles={}}var k=function(a,b){var c=["Webkit","O","Moz","ms"];if(b in a)return b;for(var d=b.charAt(0).toUpperCase()+b.slice(1),
h=b,e=c.length;e--;)if(b=c[e]+d,b in a)return b;return h},n=function(){if(window.getComputedStyle){var a=window.getComputedStyle(document.documentElement,"");return(Array.prototype.slice.call(a).join("").match(/-(moz|webkit|ms)-/)||""===a.OLink&&["","o"])[1]}}();(function(){var a=c("<div>")[0],b={webkit:"webkitTransitionEnd",moz:"transitionend",ms:"msTransitionEnd",o:"webkitTransitionEnd"},f;for(f in b)if(n===f)return b[f];if("transitionend"in a.style)return"transitionend"})();var y=!!window.navigator.userAgent.toLowerCase().match(/msie/),
m=function(){var a=Math.PI/180;return function(b){return b*a}}();(function(){var a=180/Math.PI;return function(b){return b*a}})();var r=function(){var a=Math.pow(10,3);return function(b){return Math.round(b*a)/a}}();v.prototype={center:function(a){var b=0,f=0,d=0,h=0,g=a.matrix.toArray(),d=d+(g[4]+a.def.x),h=h+(g[5]+a.def.y);if(this.scalex||this.rotatey||this.skewx)b=-(parseInt(c(a.elem).width(),10)-a.src.width)/2;if(this.scaley||this.rotatex||this.skewy)f=-(parseInt(c(a.elem).height(),10)-a.src.height)/
2;this.rotatez&&(b=-(a.elem.offsetWidth/2)+a.elem.clientWidth/2,f=-(a.elem.offsetHeight/2)+a.elem.clientHeight/2);c(a.elem).css({left:e("%spx",d),top:e("%spx",h),marginLeft:e("%spx",b),marginTop:e("%spx",f)})}};w.prototype={set:function(a,b){var f=k(this.elem.style,a);c(this.elem).css(f,b);return this},get:function(a){a=k(this.elem.style,a);return c(this.elem).css(a)},transform:function(a){a=a.toArray();for(var b=0;b<a.length;b++)a[b]=r(a[b]);this.set("transform",e("matrix(%s,%s,%s,%s,%s,%s)",a[0],
a[1],a[2],a[3],a[4],a[5]))},dxImageTransform:function(a){a=a.toArray();for(var b=0;b<a.length;b++)a[b]=r(a[b]);this.set("filter",e("progid:DXImageTransform.Microsoft.Matrix(M11=%s, M12=%s, M21=%s, M22=%s,sizingMethod='auto expand');",a[0],a[2],a[1],a[3]))},animate:function(a,b,f,d,e){this.dest.update(a);this.src.width=parseInt(c(this.elem).width(),10);this.src.height=parseInt(c(this.elem).height(),10);var g={},l;for(l in a)l in this.dest&&(g["__"+l]=this.dest[l]-this.src[l]);for(l in a)this.dest[l]||
(g[l]=a[l]);parseInt(c(this.elem).css("margin"))&&c(this.elem).css("margin","0");c(this.elem).delay(f).animate(c.extend(g,{___update:!0}),{duration:b,easing:d,complete:this.complete(this,e),step:this.update(this,new v)});c(this.elem).dequeue()},update:function(a,b){return function(c,d){var e=d.prop.replace(/__/,"");e in a.src&&(b[e]=c);"_update"!==e&&(a.matrix=new q,a.matrix=a.matrix.translate({x:b.x+a.src.x,y:b.y+a.src.y}),a.matrix=a.matrix.rotate(m(b.rotatez+a.src.rotatez)),a.matrix=null!==b.rotatex||
null!==b.rotatey?a.matrix.scale({x:Math.cos(m((b.rotatey||0)+a.src.rotatey)),y:Math.cos(m((b.rotatex||0)+a.src.rotatex))}):a.matrix.scale({x:b.scalex+a.src.scalex,y:b.scaley+a.src.scaley}),a.matrix=a.matrix.skew({x:m(b.skewx+a.src.skewx),y:m(b.skewy+a.src.skewy)}),y?(a.dxImageTransform(a.matrix),b.center(a)):a.transform(a.matrix))}},complete:function(a,b){return function(){c(a.elem).data("tween:transform",a.dest);c.proxy(b,a.elem)()}}};if(!c.cssHooks)throw"jQuery 1.4.3 or above is required for this plugin to work";
c.cssHooks.x={get:function(a,b,f){return(c(a).data("tween:transform")||d.factory()).x},set:function(a,b){c(a).tween({x:parseInt(b,10)},0)}};c.cssHooks.y={get:function(a,b,f){return(c(a).data("tween:transform")||d.factory()).y},set:function(a,b){c(a).tween({y:parseInt(b,10)},0)}};c.cssHooks.z={get:function(a,b,f){return(c(a).data("tween:transform")||d.factory()).z},set:function(a,b){c(a).tween({z:parseInt(b,10)},0)}};c.cssHooks.rotate={get:function(a,b,f){return(c(a).data("tween:transform")||d.factory()).rotatez},
set:function(a,b){c(a).tween({rotatez:parseInt(b,10)},0)}};c.cssHooks.rotatex={get:function(a,b,f){return(c(a).data("tween:transform")||d.factory()).rotatex},set:function(a,b){c(a).tween({rotatex:parseInt(b,10)},0)}};c.cssHooks.rotatey={get:function(a,b,f){return(c(a).data("tween:transform")||d.factory()).rotatey},set:function(a,b){c(a).tween({rotatey:parseInt(b,10)},0)}};c.cssHooks.rotatez={get:function(a,b,f){return(c(a).data("tween:transform")||d.factory()).rotatez},set:function(a,b){c(a).tween({rotatez:parseInt(b,
10)},0)}};c.cssHooks.scale={get:function(a,b,f){a=c(a).data("tween:transform")||d.factory();return{x:a.scalex,y:a.scaley}},set:function(a,b){c(a).tween({scalex:parseInt(b,10),scaley:parseInt(b,10)},0)}};c.cssHooks.scalex={get:function(a,b,f){return(c(a).data("tween:transform")||d.factory()).scalex},set:function(a,b){c(a).tween({scalex:parseInt(b,10)},0)}};c.cssHooks.scaley={get:function(a,b,f){return(c(a).data("tween:transform")||d.factory()).scaley},set:function(a,b){c(a).tween({scaley:parseInt(b,
10)},0)}};c.cssHooks.skew={get:function(a,b,f){a=c(a).data("tween:transform")||d.factory();return{x:a.skewx,y:a.skewy}},set:function(a,b){c(a).tween({skewx:parseInt(b,10),skewy:parseInt(b,10)},0)}};c.cssHooks.skewx={get:function(a,b,f){return(c(a).data("tween:transform")||d.factory()).skewx},set:function(a,b){c(a).tween({skewx:parseInt(b,10)},0)}};c.cssHooks.skewy={get:function(a,b,f){return(c(a).data("tween:transform")||d.factory()).skewy},set:function(a,b){c(a).tween({skewy:parseInt(b,10)},0)}};
Object.create||(Object.create=function(a){function b(){}if(1<arguments.length)throw Error("Object.create implementation only accepts the first parameter.");b.prototype=a;return new b});m=function(){var a=Math.PI/180;return function(b){return b*a}}();(function(){var a=180/Math.PI;return function(b){return b*a}})();var r=function(){var a=Math.pow(10,3);return function(b){return Math.round(b*a)/a}}(),q=function(a){this.base=a||[1,0,0,0,1,0]};q.prototype={_multiply:function(a,b,c,d,e,g,l,k,m,n,p,r){return new q([a*
l+b*n,a*k+b*p,a*m+b*r+c,d*l+e*n,d*k+e*p,d*m+e*r+g])},multiply:function(a){return this._multiply.apply(this,this.base.concat(a))},translate:function(a){return this.multiply([1,0,a.x,0,1,a.y])},rotate:function(a){var b=Math.sin(a);a=Math.cos(a);return this.multiply([a,b,0,-b,a,0])},scale:function(a){return this.multiply([a.x,0,0,0,a.y,0])},skew:function(a){return this.multiply([1,a.y||0,0,a.x||0,1,0])},toArray:function(){var a=this.base;return[a[0],a[1],a[3],a[4],a[2],a[5]]}};q.parseArray=function(a){return new q([a[0],
a[1],a[4],a[2],a[3],a[5]])};var d=function(){this.rotatez=this.rotatey=this.rotatex=this.z=this.y=this.x=0;this.scalez=this.scaley=this.scalex=1;this.skewy=this.skewx=0;this.origin="50% 50%";this.perspective="none"};d.factory=function(){switch(n){case "o":return new u;default:return new d}};d.prototype.toAbs=function(a,b){var c;if("string"===typeof b&&(c=b.match(/^\s*(\+|-)=\s*([0-9]+)\s*$/)))switch(c[1]){case "+":b=this[a]+ +c[2];break;case "-":b=this[a]-+c[2]}return+b};d.prototype.set=function(a,
b){this[a]=b;return this};d.prototype.update=function(a){for(var b in a)void 0!==this[b]&&"function"!==typeof this[b]&&this.set(b,this.toAbs(b,a[b]));return this};d.prototype.translate=function(){return e("translate(%spx,%spx)",this.x,this.y)};d.prototype.translateX=function(){return e("translateX(%spx)",this.x)};d.prototype.translateY=function(){return e("translateY(%spx)",this.y)};d.prototype.translateZ=function(){return e("translateZ(%spx)",this.z)};d.prototype.translate3d=function(){return e("translate3d(%spx,%spx,%spx)",
this.x,this.y,this.z)};d.prototype.rotateX=function(){return e("rotateX(%sdeg)",this.rotatex)};d.prototype.rotateY=function(){return e("rotateY(%sdeg)",this.rotatey)};d.prototype.rotateZ=function(){return e("rotateZ(%sdeg)",this.rotatez)};d.prototype.scale=function(){return e("scale(%s,%s)",this.scalex,this.scaley)};d.prototype.scaleX=function(){return e("scaleX(%s)",this.scalex)};d.prototype.scaleY=function(){return e("scaleY(%s)",this.scaley)};d.prototype.scaleZ=function(){return e("scaleZ(%s)",
this.scalez)};d.prototype.scale3d=function(){return e("scale3d(%s,%s,%s)",this.scalex,this.scaley,this.scalez)};d.prototype.skew=function(){return e("skew(%sdeg,%sdeg)",this.skewx,this.skewy)};d.prototype.skewX=function(){return e("skewX(%sdeg)",this.skewx)};d.prototype.skewY=function(){return e("skewY(%sdeg)",this.skewy)};d.prototype.toString=function(){return[this.translate3d(),this.rotateX(),this.rotateY(),this.rotateZ(),this.scale(),this.skewX(),this.skewY()].join(" ")};var u=function(){d.call(this)};
u.prototype=Object.create(d.prototype);u.prototype.toString=function(){return[this.translate(),this.rotateZ(),this.scale(),this.skewX(),this.skewY()].join(" ")};p.cubicBezier={def:this["ease-out-quad"],"in":"ease-in",out:"ease-out","in-out":"ease-in-out",linear:"cubic-bezier(0.250, 0.250, 0.750, 0.750)","ease-in-quad":"cubic-bezier(0.550, 0.085, 0.680, 0.530)","ease-in-cubic":"cubic-bezier(0.550, 0.055, 0.675, 0.190)","ease-in-quart":"cubic-bezier(0.895, 0.030, 0.685, 0.220)","ease-in-quint":"cubic-bezier(0.755, 0.050, 0.855, 0.060)",
"ease-in-sine":"cubic-bezier(0.470, 0.000, 0.745, 0.715)","ease-in-expo":"cubic-bezier(0.950, 0.050, 0.795, 0.035)","ease-in-circ":"cubic-bezier(0.600, 0.040, 0.980, 0.335)","ease-in-back":"cubic-bezier(0.600, -0.280, 0.735, 0.045)","ease-out-quad":"cubic-bezier(0.250, 0.460, 0.450, 0.940)","ease-out-cubic":"cubic-bezier(0.215, 0.610, 0.355, 1.000)","ease-out-quart":"cubic-bezier(0.165, 0.840, 0.440, 1.000)","ease-out-quint":"cubic-bezier(0.230, 1.000, 0.320, 1.000)","ease-out-sine":"cubic-bezier(0.390, 0.575, 0.565, 1.000)",
"ease-out-expo":"cubic-bezier(0.190, 1.000, 0.220, 1.000)","ease-out-circ":"cubic-bezier(0.075, 0.820, 0.165, 1.000)","ease-out-back":"cubic-bezier(0.175, 0.885, 0.320, 1.275)","ease-in-out-quad":"cubic-bezier(0.455, 0.030, 0.515, 0.955)","ease-in-out-cubic":"cubic-bezier(0.645, 0.045, 0.355, 1.000)","ease-in-out-quart":"cubic-bezier(0.770, 0.000, 0.175, 1.000)","ease-in-out-quint":"cubic-bezier(0.860, 0.000, 0.070, 1.000)","ease-in-out-sine":"cubic-bezier(0.445, 0.050, 0.550, 0.950)","ease-in-out-expo":"cubic-bezier(1.000, 0.000, 0.000, 1.000)",
"ease-in-out-circ":"cubic-bezier(0.785, 0.135, 0.150, 0.860)","ease-in-out-back":"cubic-bezier(0.680, -0.550, 0.265, 1.550)"};p.prototype={set:function(a,b){var c=k(this.elem.style,a);this.styles[c]=b;return this},get:function(a){a=k(this.elem.style,a);return this.styles[a]},duration:function(a,b){if(void 0===a)return parseInt(this.get("transition-duration"),10);this.set("transition-duration",e("%s%s",a,void 0===b?"ms":""));return this},delay:function(a,b){if(void 0===a)return parseInt(this.get("transition-delay"),
10);this.set("transition-delay",e("%s%s",a,void 0===b?"ms":""));return this},easing:function(a){if(void 0===a)return this.get("transition-timing-function");this.set("transition-timing-function",p.cubicBezier[a]);return this},property:function(a){if(void 0===a)return this.get("transition-property");this.set("transition-property",a);return this},style:function(a){if(void 0===a)return this.get("transform-style");this.set("transform-style",a);return this},transform:function(a){if(void 0===a)return this.get("transform");
this.set("transform",a);return this},transit:function(a,b,d,e){this.duration(a);this.delay(b);this.easing(d);c(this.elem).css(this.styles);if(0===this.duration())for(b=0,a=k(this.elem.style,"transition-duration");50<++b&&0!==parseInt(c(this.elem).css(a),10););setTimeout(c.proxy(this.complete(this,e),this.elem),this.duration());return this},complete:function(a,b){return function(){c.proxy(b,this)();c(this).dequeue();0===c(this).queue().length&&a.clear()}},clear:function(){this.duration("","").delay("",
"").easing("").property("");c(this.elem).css(this.styles)}};c.fn.tween=function(a,b,d,e){"function"===typeof b&&(e=b,b=void 0);"function"===typeof d&&(e=d,d=void 0);switch(typeof b){case "number":break;case "string":b=c.fx.speeds[b]||c.fx.speeds._default;break;default:b=c.fx.speeds._default}var h=c.extend(!0,{},a),g;for(g in a){switch(g){case "rotate":h.rotatez=a[g];break;case "scale":h.scalex=h.scaley=a[g];break;case "skew":h.skewx=h.skewy=a[g];break;default:continue}delete h[g]}return this.queue(z({props:h||
{},duration:b,delay:0,easing:d||"def",style:"flat",property:"all",complete:e||function(){}}))};c.fn.tween.debug={animateType:""};k=function(a,b){var c=["Webkit","O","Moz","ms"];if(b in a)return b;for(var d=b.charAt(0).toUpperCase()+b.slice(1),e=b,g=c.length;g--;)if(b=c[g]+d,b in a)return b;return e};n=function(){if(window.getComputedStyle){var a=window.getComputedStyle(document.documentElement,"");return(Array.prototype.slice.call(a).join("").match(/-(moz|webkit|ms)-/)||""===a.OLink&&["","o"])[1]}}();
(function(){var a=c("<div>")[0],b={webkit:"webkitTransitionEnd",moz:"transitionend",ms:"msTransitionEnd",o:"webkitTransitionEnd"},d;for(d in b)if(n===d)return b[d];if("transitionend"in a.style)return"transitionend"})();y=!!window.navigator.userAgent.toLowerCase().match(/msie/)})(jQuery);
